# End-to-End Financial Analysis and Forecasting

## Project Purpose

This notebook presents a full financial analysis and forecasting workflow using simulated company data. 

The analysis answers practical business questions:

1. What is driving revenue?
2. What is driving profit?
3. Which products and regions are most profitable?
4. Where is the company beating or missing budget?
5. Are discounts helping or hurting profitability?
6. Which customers are most valuable?
7. How efficiently does the company convert sales into cash?
8. Can monthly revenue be forecasted?
9. What actions should management take?

The project uses invoice-level data, monthly budget data, financial statement data, and macroeconomic indicators.

### 1. Import Libraries

In [1]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

from statsmodels.tsa.holtwinters import ExponentialSmoothing

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

# Project folders
DATA_DIR = Path("../data")
FIGURES_DIR = Path("../figures")
OUTPUTS_DIR = Path("../outputs")

FIGURES_DIR.mkdir(exist_ok=True)
OUTPUTS_DIR.mkdir(exist_ok=True)

### 2. Load the Data

This project uses four related datasets.

1. `simulated_financial_transactions.csv`: invoice-level data
2. `monthly_budget_targets.csv`: budgeted revenue and costs
3. `monthly_financial_statements.csv`: monthly accounting and cash flow metrics
4. `macro_indicators_monthly.csv`: external variables for forecasting

In [3]:
transactions = pd.read_csv(DATA_DIR / "simulated_financial_transactions.csv")
budget = pd.read_csv(DATA_DIR / "monthly_budget_targets.csv")
financials = pd.read_csv(DATA_DIR / "monthly_financial_statements.csv")
macro = pd.read_csv(DATA_DIR / "macro_indicators_monthly.csv")

print("Transactions shape:", transactions.shape)
print("Budget shape:", budget.shape)
print("Financial statements shape:", financials.shape)
print("Macro indicators shape:", macro.shape)

Transactions shape: (120300, 21)
Budget shape: (1440, 8)
Financial statements shape: (72, 26)
Macro indicators shape: (72, 7)

In [4]:
transactions.head()

,invoice_id,invoice_date,fiscal_year,fiscal_month,region,product_line,sales_channel,customer_segment,industry,customer_id,sales_rep_id,units,unit_price,discount_rate,net_revenue,cogs,gross_profit,gross_margin_pct,payment_terms,days_to_collect,is_returned
0,1,2023-09-08,2023,9,North America,Data Platform,Direct Sales,SMB,Retail,119927,545,2,"2,240.67",0.05,"3,063.72",808.38,"2,255.34",0.74,90,99.10,0
1,2,2023-01-27,2023,1,North America,Data Platform,Partner,SMB,Retail,110883,545,4,"2,217.11",0.05,"6,064.06","2,237.89","3,826.16",0.63,15,14.10,0
2,3,2024-11-01,2024,11,North America,Professional Services,Direct Sales,SMB,Education,128755,523,3,"1,699.93",0.14,"3,140.53","1,917.16","1,223.38",0.39,30,33.20,0
3,4,2025-11-24,2025,11,Europe,Subscription,Direct Sales,SMB,Retail,117634,562,2,"1,035.47",0.08,"1,374.94",341.35,"1,033.60",0.75,15,16.70,0
4,5,2023-02-21,2023,2,Latin America,Professional Services,Enterprise Account,Mid-Market,Manufacturing,115491,599,3,"2,293.54",0.06,"6,474.79","4,042.89","2,431.90",0.38,15,17.10,0

### 3. Initial Data Inspection

Before doing any financial analysis, a professional analyst should inspect the data for:

- Missing values
- Duplicate rows
- Incorrect data types
- Inconsistent categorical values
- Outliers
- Date problems

In [5]:
def inspect_dataframe(df, name):
    print(f"\n==================== {name.upper()} ====================")
    print("Shape:", df.shape)
    print("\nData types:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isna().sum().sort_values(ascending=False).head(15))
    print("\nDuplicate rows:", df.duplicated().sum())

inspect_dataframe(transactions, "transactions")
inspect_dataframe(budget, "budget")
inspect_dataframe(financials, "financials")
inspect_dataframe(macro, "macro")

==================== TRANSACTIONS ====================
Shape: (120300, 21)

Data types:
invoice_id            int64
invoice_date            str
fiscal_year           int64
fiscal_month          int64
region                  str
product_line            str
sales_channel           str
customer_segment        str
industry                str
customer_id           int64
sales_rep_id          int64
units                 int64
unit_price          float64
discount_rate       float64
net_revenue         float64
cogs                float64
gross_profit        float64
gross_margin_pct    float64
payment_terms         int64
days_to_collect     float64
is_returned           int64
dtype: object

Missing values:
gross_margin_pct    1806
days_to_collect     1805
discount_rate       1805
invoice_id             0
units                  0
payment_terms          0
gross_profit           0
cogs                   0
net_revenue            0
unit_price             0
sales_rep_id           0
invoice_date           0
customer_id            0
industry               0
customer_segment       0
dtype: int64

Duplicate rows: 300

==================== BUDGET ====================
Shape: (1440, 8)

Data types:
month                       str
region                      str
product_line                str
budget_revenue          float64
budget_cogs             float64
budget_gross_profit     float64
budget_units              int64
budget_discount_rate    float64
dtype: object

Missing values:
month                   0
region                  0
product_line            0
budget_revenue          0
budget_cogs             0
budget_gross_profit     0
budget_units            0
budget_discount_rate    0
dtype: int64

Duplicate rows: 0

==================== FINANCIALS ====================
Shape: (72, 26)

Data types:
month                            str
revenue                      float64
cogs                         float64
gross_profit                 float64
units                          int64
active_customers               int64
return_rate                  float64
avg_days_to_collect          float64
sales_marketing_expense      float64
r_and_d_expense              float64
g_and_a_expense              float64
total_opex                   float64
ebitda                       float64
depreciation_amortization    float64
operating_income             float64
interest_expense             float64
tax_expense                  float64
net_income                   float64
accounts_receivable          float64
inventory                    float64
accounts_payable             float64
capex                        float64
free_cash_flow               float64
gross_margin                 float64
ebitda_margin                float64
net_margin                   float64
dtype: object

Missing values:
month                        0
revenue                      0
ebitda_margin                0
gross_margin                 0
free_cash_flow               0
capex                        0
accounts_payable             0
inventory                    0
accounts_receivable          0
net_income                   0
tax_expense                  0
interest_expense             0
operating_income             0
depreciation_amortization    0
ebitda                       0
dtype: int64

Duplicate rows: 0

==================== MACRO ====================
Shape: (72, 7)

Data types:
month                            str
interest_rate                float64
inflation_rate               float64
unemployment_rate            float64
business_confidence_index    float64
market_index                 float64
exchange_rate_index          float64
dtype: object

Missing values:
month                        0
interest_rate                0
inflation_rate               0
unemployment_rate            0
business_confidence_index    0
market_index                 0
exchange_rate_index          0
dtype: int64

Duplicate rows: 0

### 4. Data Cleaning

Cleaning steps:

1. Convert date columns to datetime.
2. Remove duplicate invoice rows.
3. Standardize text columns.
4. Fill missing financial rates with appropriate values.
5. Recalculate gross margin where needed.
6. Create monthly date variables.

In [7]:
# Convert dates
transactions["invoice_date"] = pd.to_datetime(transactions["invoice_date"])
budget["month"] = pd.to_datetime(budget["month"])
financials["month"] = pd.to_datetime(financials["month"])
macro["month"] = pd.to_datetime(macro["month"])

In [8]:
# Remove duplicates
before = len(transactions)
transactions = transactions.drop_duplicates()
after = len(transactions)

print(f"Duplicate rows removed: {before - after}")

Duplicate rows removed: 300

In [9]:
# Clean text columns
text_cols = transactions.select_dtypes(include="object").columns

for col in text_cols:
    transactions[col] = transactions[col].str.strip().str.title()

In [10]:
# Fill missing discount rate with median
transactions["discount_rate"] = transactions["discount_rate"].fillna(
    transactions["discount_rate"].median()
)

In [12]:
# Fill missing days to collect by payment terms group with median
transactions["days_to_collect"] = transactions.groupby("payment_terms")["days_to_collect"].transform(
    lambda x: x.fillna(x.median())
)

In [13]:
# Recalculate gross margin where missing
transactions["gross_margin_pct"] = transactions["gross_margin_pct"].fillna(
    transactions["gross_profit"] / transactions["net_revenue"]
)

In [14]:
# Create time variables
transactions["month"] = transactions["invoice_date"].dt.to_period("M").dt.to_timestamp()
transactions["year"] = transactions["invoice_date"].dt.year
transactions["quarter"] = transactions["invoice_date"].dt.quarter
transactions["month_name"] = transactions["invoice_date"].dt.month_name()

In [15]:
# Save cleaned data
transactions.to_csv(OUTPUTS_DIR / "cleaned_financial_transactions.csv", index=False)

transactions.head()

,invoice_id,invoice_date,fiscal_year,fiscal_month,region,product_line,sales_channel,customer_segment,industry,customer_id,sales_rep_id,units,unit_price,discount_rate,net_revenue,cogs,gross_profit,gross_margin_pct,payment_terms,days_to_collect,is_returned,month,year,quarter,month_name
0,1,2023-09-08,2023,9,North America,Data Platform,Direct Sales,Smb,Retail,119927,545,2,"2,240.67",0.05,"3,063.72",808.38,"2,255.34",0.74,90,99.10,0,2023-09-01,2023,3,September
1,2,2023-01-27,2023,1,North America,Data Platform,Partner,Smb,Retail,110883,545,4,"2,217.11",0.05,"6,064.06","2,237.89","3,826.16",0.63,15,14.10,0,2023-01-01,2023,1,January
2,3,2024-11-01,2024,11,North America,Professional Services,Direct Sales,Smb,Education,128755,523,3,"1,699.93",0.14,"3,140.53","1,917.16","1,223.38",0.39,30,33.20,0,2024-11-01,2024,4,November
3,4,2025-11-24,2025,11,Europe,Subscription,Direct Sales,Smb,Retail,117634,562,2,"1,035.47",0.08,"1,374.94",341.35,"1,033.60",0.75,15,16.70,0,2025-11-01,2025,4,November
4,5,2023-02-21,2023,2,Latin America,Professional Services,Enterprise Account,Mid-Market,Manufacturing,115491,599,3,"2,293.54",0.06,"6,474.79","4,042.89","2,431.90",0.38,15,17.10,0,2023-02-01,2023,1,February